# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Unsolved Machine Learning'
tagline:          ''
description:      'A curated list of unanswered questions in machine learning.'
url:              http://unsolved.ml
baseurl:          /

author:
  name:           'Christopher Frederickson'
  url:            https://twitter.com/chrisfreder

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/adversarialml/unsolved-website
